[package]
# TODO(1) fix `authors` and `name` if you didn't use `cargo-generate`
authors = ["asserthq <sanya2003ogorodov@gmail.com>"]
name = "sandbox"
edition = "2024"
version = "0.1.0"

[[bin]]
name = "blinky"
test = false

[[bin]]
name = "lora_receive"
test = false

[[bin]]
name = "lora_send"
test = false

[lib]
name = "sandbox_lib"
harness = false

[dependencies]
common-lib = { path = "../common-lib" }

embassy-stm32 = { version = "0.6.0", features = [ "defmt", "stm32f303vc", "unstable-pac", "memory-x", "time-driver-any", "exti" ]  }
embassy-executor = { version = "0.10.0", features = ["platform-cortex-m", "executor-thread", "defmt"] }
embassy-time = { version = "0.5.1", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }

cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.0"

# LOGGER
defmt = "1.0.1"
defmt-rtt = "1.0.0"

# DEBUG
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
semihosting = "0.1.25"
