[package]
# TODO(1) fix `authors` and `name` if you didn't use `cargo-generate`
authors = ["asserthq <sanya2003ogorodov@gmail.com>"]
name = "bsp-stm32f3-disco"
edition = "2024"
version = "0.1.0"

[lib]
harness = false

[dependencies]
embassy-stm32 = { version = "0.6.0", features = [ "defmt", "stm32f103c8", "unstable-pac", "memory-x", "time-driver-any", "exti" ]  }

defmt = "1.0.1"
defmt-rtt = "1.0.0"

cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.0"
embedded-hal = "0.2.6"
embedded-hal-bus = { version = "0.3.0", features = ["defmt-03", "async"] }
panic-probe = { version = "1.0.0", features = ["print-defmt"] }

# LORA
lora-phy = { version = "3.0.1", features = ["lorawan-radio"] }

one-wire-bus = "0.1.1"
ds18b20 = "0.1.1"

[dev-dependencies]
defmt-test = "0.3"
