[package]
authors = ["asserthq <sanya2003ogorodov@gmail.com>"]
name = "core"
edition = "2024"
version = "0.1.0"

[lib]
harness = false

[dependencies]
# HAL TRAITS
embedded-hal = "0.2.6"
embedded-hal-bus = { version = "0.3.0", features = ["defmt-03", "async"] }
one-wire-bus = "0.1.1"

# DRIVERS
lora-phy = { version = "3.0.1", features = ["lorawan-radio"] }
ds18b20 = "0.1.1"

# LOGGER
defmt = "1.0.1"
