[package]
authors = ["asserthq <sanya2003ogorodov@gmail.com>"]
name = "asp868"
edition = "2024"
version = "0.1.0"

[dependencies]
sat_core = { package = "sat-core", path = "../core" }
sat_drivers = { package = "sat-drivers", path = "../drivers" }

embassy-stm32 = { version = "0.6.0", features = [ "defmt", "stm32f072cb", "unstable-pac", "memory-x", "time-driver-any", "time", "exti" ] }
embassy-executor = { version = "0.10.0", features = ["platform-cortex-m", "executor-thread", "defmt"] }
embassy-time = { version = "0.5.1", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }

cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.0"

defmt = "1.0.1"
defmt-rtt = "1.0.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }

embedded-hal-bus = { version = "0.3.0", features = ["defmt-03", "async"] }
heapless = { version = "0.9.3", features = ["serde", "defmt"] }
postcard = { version = "1.1.3", default-features = false, features = ["defmt"] }