[package]
# TODO(1) fix `authors` and `name` if you didn't use `cargo-generate`
authors = ["asserthq <sanya2003ogorodov@gmail.com>"]
name = "sandbox-mcu"
edition = "2024"
version = "0.1.0"

[lib]
name = "sandbox_lib"
harness = false

[[bin]]
name = "uart"

[[bin]]
name = "uart_echo"

[[bin]]
name = "satellite"

[[bin]]
name = "gs"

[[bin]]
name = "client"

[[bin]]
name = "lora_868_tx"

[[bin]]
name = "lora_868_rx"

[[bin]]
name = "mmc5983ma"

[[bin]]
name = "tx_flash"

[[bin]]
name = "flash_read"

[dependencies]
sat_core = { package = "sat-core", path = "../core" }
sat_drivers = { package = "sat-drivers", path = "../drivers" }

embassy-stm32 = { version = "0.6.0", features = [ "defmt", "stm32f401rc", "unstable-pac", "memory-x", "time-driver-any", "time", "exti" ]  }
embassy-executor = { version = "0.10.0", features = ["platform-cortex-m", "executor-thread", "defmt"] }
embassy-time = { version = "0.5.1", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
embassy-futures = { version = "0.1.2", features = ["defmt"] }

cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.0"

# LOGGER
defmt = "1.0.1"
defmt-rtt = "1.0.0"

# DEBUG
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
defmt-test = "0.5.0"
embedded-hal = { version = "1.0.0", features = ["defmt-03"] }
embedded-hal-async = { version = "1.0.0", features = ["defmt-03"] }
embedded-hal-bus = { version = "0.3.0", features = ["defmt-03", "async"] }
embedded-io-async = "0.7"
serde = { version = "1", default-features = false, features = ["derive"] }
postcard = { version = "1.1.3", default-features = false, features = ["defmt"] }
heapless = { version = "0.9.3", features = ["serde", "defmt"] }

lora-phy = "3.0.1"
mmc5983_rs = { version = "0.0.1", features = ["async"] }
